name: IMGT-MPN
channels:
- pytorch 
- dglteam
- conda-forge
- fragcolor
- anaconda
- defaults
dependencies:
- cudatoolkit=11.1  
- cudnn=8.9.2.26=cuda11_0
- python>=3.8
- python-dateutil=2.8.0
- pip=19.2.3
- pytorch=1.10.0+cu111
- torchvision==0.11.0  
- pillow==10.3.0
- dgl-cuda11.1=0.9.1
- numpy=1.24.4
- matplotlib=3.5.0
- tensorboard=2.16.0
- tensorboardx=2.6.2
- future=1.0.0
- absl-py
- networkx=2.8.8
- scikit-learn=1.3.2
- scipy=1.10.1
- notebook=7.2.0
- h5py=3.11.0
- mkl=2023.1.0
- ipykernel=6.29.3
- ipython=8.12.0
- ipython_genutils=0.2.0
- ipywidgets=8.1.2
- jupyter=1.0.0
- jupyter_client=8.6.1
- jupyter_console=6.6.3
- jupyter_core=5.7.2
- plotly=5.22.0
- scikit-image=0.19.3
- requests==2.31.0
- tqdm==4.66.4
- rdkit==2024.3.2
- pip:
  - tensorflow-gpu==2.1.0
  - tensorflow-estimator==2.1.0
  - tensorboard==2.1.1
  - ogb==1.3.6
